apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/ibrahiemalbarki-gmail-com/flogo-demo-k8:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/ibrahiemalbarki-gmail-com/flogo-demo-k8:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: flogo-demo-k8
        chartPath: charts/flogo-demo-k8
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/ibrahiemalbarki-gmail-com/flogo-demo-k8"
          image.tag: "{{.DIGEST_HEX}}"
